#!/usr/bin/env python3
"""Generate Minimal Mistakes category pages from _data/navigation.yml.

Requires Python 3.10+ and PyYAML. Run from any directory:
    python _scripts/sync_categories.py --check
    python _scripts/sync_categories.py
"""
import argparse
import hashlib
import re
import sys
from pathlib import Path

import yaml

MARKER = "# Generated by sync_categories.py; DO NOT EDIT."


class UniqueLoader(yaml.SafeLoader):
    pass


def unique_mapping(loader, node, deep=False):
    result = {}
    for key_node, value_node in node.value:
        key = loader.construct_object(key_node, deep=deep)
        if key in result:
            raise ValueError(f"Duplicate YAML key: {key!r}")
        result[key] = loader.construct_object(value_node, deep=deep)
    return result


UniqueLoader.add_constructor(
    yaml.resolver.BaseResolver.DEFAULT_MAPPING_TAG, unique_mapping
)


def read_yaml(text):
    return yaml.load(text, Loader=UniqueLoader)


def required(item, key, location):
    value = item.get(key)
    if not isinstance(value, str) or not value.strip():
        raise ValueError(f"{location}: non-empty {key!r} is required")
    if value != value.strip():
        raise ValueError(f"{location}: {key!r} has leading/trailing whitespace")
    return value


def plan(root):
    data = read_yaml((root / "_data/navigation.yml").read_text(encoding="utf-8-sig"))
    if not isinstance(data, dict) or not isinstance(data.get("sidebar-category"), list):
        raise ValueError("navigation.yml: sidebar-category must be a list (use [] to clear)")
    config = read_yaml((root / "_config.yml").read_text(encoding="utf-8-sig"))
    if not isinstance(config, dict) or "_pages" not in (config.get("include") or []):
        raise ValueError("_config.yml must include _pages in its include list")
    pages = {}
    urls = set()
    categories = set()

    def visit(items, location):
        for index, item in enumerate(items):
            loc = f"{location}[{index}]"
            if not isinstance(item, dict):
                raise ValueError(f"{loc}: expected a mapping")
            title = required(item, "title", loc)
            if "children" in item:
                if not isinstance(item["children"], list):
                    raise ValueError(f"{loc}: children must be a list")
                if "url" in item or "category" in item:
                    raise ValueError(f"{loc}: group headings cannot have url/category")
                visit(item["children"], loc + ".children")
                continue
            # Existing empty headings such as GRAPHICS are allowed.
            if "url" not in item and "category" not in item:
                continue
            url = required(item, "url", loc)
            category = required(item, "category", loc)
            if not re.fullmatch(r"/categories/[A-Za-z0-9_-]+/", url):
                raise ValueError(f"{loc}: url must be /categories/ASCII-slug/")
            if url.casefold() in urls:
                raise ValueError(f"{loc}: duplicate URL: {url}")
            if category in categories:
                raise ValueError(f"{loc}: duplicate category: {category}")
            urls.add(url.casefold())
            categories.add(category)
            name = hashlib.sha256(url.encode()).hexdigest()[:20] + ".md"
            front = {"title": title, "layout": "category", "permalink": url,
                     "taxonomy": category, "author_profile": item.get("author_profile", False),
                     "sidebar": {"nav": "sidebar-category"}}
            if not isinstance(front["author_profile"], bool):
                raise ValueError(f"{loc}: author_profile must be true or false")
            pages[name] = "---\n" + MARKER + "\n" + yaml.safe_dump(
                front, allow_unicode=True, sort_keys=False
            ) + "---\n"

    visit(data["sidebar-category"], "sidebar-category")
    output = root / "_pages/generated-categories"
    if output.is_symlink() or (root / "_pages").is_symlink():
        raise ValueError("Output directories must not be symbolic links")
    managed = []
    if output.exists():
        for path in output.iterdir():
            if path.is_symlink() or not path.is_file() or path.suffix != ".md":
                raise ValueError(f"Unexpected item in generated directory: {path}")
            if not path.read_text(encoding="utf-8").startswith("---\n" + MARKER + "\n"):
                raise ValueError(f"Refusing to overwrite unmanaged file: {path}")
            managed.append(path)
    # Detect old manually created category pages before generating duplicates.
    for path in root.rglob("*"):
        if path.suffix.lower() not in {".md", ".markdown", ".html"}:
            continue
        relative = path.relative_to(root)
        if any(p in {".git", "_site", "vendor", "node_modules", "_posts"} for p in relative.parts):
            continue
        if path.parent == output:
            continue
        text = path.read_text(encoding="utf-8-sig")
        match = re.match(r"\A---\r?\n(.*?)\r?\n---(?:\r?\n|$)", text, re.S)
        if match:
            front = read_yaml(match.group(1))
            if isinstance(front, dict):
                link = front.get("permalink")
                if isinstance(link, str) and (link.rstrip("/") + "/").casefold() in urls:
                    raise ValueError(f"Existing page conflicts with generated URL: {relative}")
    return output, pages, managed


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--root", type=Path, default=Path(__file__).resolve().parent.parent,
                        help="Repository root (default: parent of _scripts directory)")
    parser.add_argument("--check", action="store_true", help="Validate only; do not change files")
    args = parser.parse_args()
    try:
        output, pages, managed = plan(args.root.resolve())
        stale = [p for p in managed if p.name not in pages]
        if not args.check:
            output.mkdir(parents=True, exist_ok=True)
            for name, content in pages.items():
                (output / name).write_text(content, encoding="utf-8", newline="\n")
            for path in stale:
                path.unlink()
        print(f"{'Validated' if args.check else 'Generated'} {len(pages)} categories; "
              f"{'would remove' if args.check else 'removed'} {len(stale)} obsolete pages.")
        return 0
    except (ValueError, OSError, yaml.YAMLError, TypeError) as exc:
        print(f"Category sync failed: {exc}", file=sys.stderr)
        return 1


if __name__ == "__main__":
    sys.exit(main())
